version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
